spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    uri: mongodb://localhost:27017/userdb
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
keycloak:
  admin:
    username: user
    password: user123
    server-url: http://localhost:8444
    realm: app-gateway
    client-id: ecom-app-client-pkce
    client-uid: d715126d-c5a1-424a-b964-16dec0d6e057