spring:
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  mongodb:
    uri: ${MONGO_URI}
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      export: ${ZIPKIN_URL}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
keycloak:
  admin:
    username: user
    password: user123
    server-url: http://keycloak:8080
    realm: app-gateway
    client-id: ecom-app-client-pkce
    client-uid: d715126d-c5a1-424a-b964-16dec0d6e057