spring:
  application:
    name: configserver
  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\java-application-ecom\configserver\src\main\resources\config
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'